# Lifespan start
# 这个参数不支持热更新
[Lifespan]
life_cycle = 5  # 服务存活的时间，小于等于0的不启动定时功能
wait_for_exit = 1  # 关闭服务的时候可等待的时间
exit_timeout = 1  # 关闭服务时的超时等待时间
# Lifespan end

# Proxy start
# 此参数支持热更新
[Proxy]
# mitmproxy指令
#command = [
#    "mitmproxy",
#    "-s", "test_1.py",
#    "-s", "test_2.py",
#    "-p", "8888"
#]
auto_start = false
startup_command = "mitmweb -p 8080"
adapt_pattern = true
fallback_pattern = "mitmweb"

# Proxy end
